### ISSUE TITLE
Update bower dependency to 1.3

### ISSUE THREAD

**Issue by AidasK** [yatskevich/grunt-bower-task#112]
https://github.com/yatskevich/grunt-bower-task/blob/devel/package.json#L37

https://github.com/bower/bower/releases

**Comment by AndrewDryga** [comment]
Updated issues in clone: https://github.com/AndrewDryga/grunt-bower-installer
This repo is forbidden by author

**Comment by nijikokun** [comment]
So it appears that this repo hasn't been updated in a long time, and it appears the one above me has, which one to use?

**Comment by ktilcu** [comment]
Looks like this is done..

**Comment by akrawchyk** [comment]
:thumbsup:

**Comment by codewithtyler** [comment]
The Bower dependency was recently updated to v1.7.9.
