### ISSUE TITLE
Update to bower 1.3.4

### ISSUE THREAD

**Issue by akhileshgupta** [yatskevich/grunt-bower-task#116]
Bower just fixed a bug for cyclic dependency in 1.3.4. Should update the dependency to consume the latest fixes.

**Comment by mhulse** [comment]
+1, but `v1.3.8` is out and fixes problem as described in #122.

**Comment by jonnyzzz** [comment]
The only working bower for the fresh node is 1.3.8. Please update the version

**Comment by mhulse** [comment]
Not sure if @yatskevich is able to work on this code. Last commit was Nov 2013.

Is there anyone out there that could help keep this repo updated? Maybe @yatskevich could give some folks access to handle pull requests and other issues?

With that said, I kinda would like to get my code working. Anyone know of an alternative to grunt-bower-task?

I found this one:

https://github.com/timmywil/grunt-bowercopy

But it looks more involved than what I think I'd prefer.

**Comment by yatskevich** [comment]
@mhulse you're reading my mind. I must admit that I don't have time to maintain the project and really  want to find trustworthy successor.
We've published a roadmap and have several design ideas for the future releases.

So, if you'd like to help, I can give you write-permissions for the repo.

**Comment by mhulse** [comment]
Hi @yatskevich thanks for the quick reply. :+1: 

I figured you were busy. I can completely sympathize with you on that one (I don't own any popular repos, but I can only imagine how time consuming it must be to maintain a popular one like grunt-bower-task).

I'm interested in helping, but the only problem I have is that I'm not very familiar with pure Node projects. I'm not sure if I'd be a good fit for writing new features or checking PRs for code quality. With that said, I'm sure I could help out with basic "bump node version" PRs/requests (though, fixing more complex issues that might arise with a version bump could be a problem for me).

With that said, I'll fork your code and play with it a bit this weekend to see how to do a build. :+1: 

In the meantime, **are there any other trustworthy GH users out there (preferably with Node/Grunt experience), that would want to help out with maintenance of this repo?** :octocat:

Thanks again @yatskevich! Glad to know you're still around. Thanks for sharing this code with the rest of us. :)
