### ISSUE TITLE
grunt bower install jquery -verbose results in error

### ISSUE THREAD

**Issue by agdev** [yatskevich/grunt-bower-task#120]
Hi,
I installed latest grunt, bower, and grunt-bower-task.
My grunt initconfig:
bower: {
            install: {
                options: {
                    targetDir: './components',
                    install: false,
                    layout:'byComponent',/\* function (type, component) {
                        var renamedType = type;
                        if (type == 'js') renamedType = 'scripts';
                        else if (type == 'css') renamedType = 'styles';

```
                    return path.join(component, renamedType);
                },*/
                bowerOptions: {forceLatest:true}
            }
        }
    }
```

when I run grunt bower install jquery -verbose 
getting: "Warning: Task "jquery" not found. Use --force to continue."
am I missing something here? or there is an issue?

**Comment by yatskevich** [comment]
Hi @agdev, 

grunt-bower-task doesn't provide interactive mode, so you have to use `bower install jquery` directly or specify your dependencies in `bower.json`.

**Comment by agdev** [comment]
Ok, I installed jquery w/ bower, How do I specify that I want just jquery to be copied?
