### ISSUE TITLE
Fatal error: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by kharandziuk** [yatskevich/grunt-bower-task#135]
Below my `bower.json` I remove everything except only one package which causes problem.

```
{
  "name": "client",
  "authors": [],
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "node-assert": "*"
  },
  "devDependencies": { }
}
```

This the result of `grunt bower --verbose --stack`

```
Running "bower:install" (bower) task
Verifying property bower.install exists in config...OK
File: [no files]
Options: cleanTargetDir, cleanBowerDir=false, targetDir="static/components", layout="byComponent", install, verbose=false, copy, bowerOptions={}
>> Cleaned target dir /home/hami/projects/work/multiad/project/static/components
bower not-cached git://github.com/Jxck/assert.git#*
bower resolve git://github.com/Jxck/assert.git#*
bower checkout master
Fatal error: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
  at path.js:360:15
  at Array.filter (native)
  at Object.exports.join (path.js:358:36)
  at GitHubResolver.GitResolver._cleanup (/home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/lib/core/resolvers/GitResolver.js:185:26)
  at /home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/lib/core/resolvers/GitResolver.js:74:25
  at Promise.apply (/home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/node_modules/q/q.js:1122:26)
  at Promise.promise.promiseDispatch (/home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/node_modules/q/q.js:752:41)
  at /home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/node_modules/q/q.js:1337:14
  at flush (/home/hami/projects/work/multiad/project/node_modules/grunt-bower-task/node_modules/bower/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:419:13)
```

it looks like it's a problem with node-assert package  but It will be better to have some more meaningful message about it

**Comment by kharandziuk** [comment]
the same issue appears if I add 
`"choosen": "https://github.com/harvesthq/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip"` as dependency
I discover this issue with grunt-bower-task@0.3.4
And everything works correctly if I just do `bower install`

**Comment by jeroenpelgrims** [comment]
Had this problem yesterday, It's cause the current node version (v0.10.31) has problems with older bower versions (anything under 1.3.4 iirc). 
grunt-bower-task 0.3.4 has a dependency on "bower": "~1.2.0" causing problems.

If you **upgrade to grunt-bower-task 4.0** your problems should be solved.
The dependency on bower was upgraded to ~1.3.0 => currently resolves to 1.3.9 here.

The reason that it works if you use `bower install` manually is most likely because you have a newer (> 1.3.8) bower version installed globally.

**Comment by anutron** [comment]
I'm having a similar issue. It's complaining about `GitResolver.js:198:26`

I threw a debug line there: 

``` javascript
this._logger.warn('temp dir: ' + this._tempDir);
    var gitFolder = path.join(this._tempDir, '.git');
```

and got this:

```
temp dir: /var/folders/6r/gvmlnvjx0c5gtzqj0syqrntr0000gn/T/aaron/bower/bootstrap-2-48384-rV1RXH,function () {
    if (called) {
      return;
    }

    removeFunction(path);

    called = true;
  } undefined
```

So somehow the temp directory path is getting a function.toString in it...

**Comment by anutron** [comment]
note that updating npm, bower, and grunt-bower-task haven't fixed the problem

**Comment by dlethin** [comment]
For what it's worth, I updated my package.json to use  "grunt-bower-task": "^0.4.0" and ran npm update and this problem went away for me.

**Comment by Glavin001** [comment]
I can also confirm that updating `grunt-bower-task` to `^0.4.0` resolves this bug. Thank you.

**Comment by xiaoshao** [comment]
I have the same problem, and my nodejs is `v0.12.7` and my bower version is `1.4.1`.
And grunt-bower-task is `^0.4.0`.

And in the gruntjs issue https://github.com/gruntjs/grunt/issues/1321 , they think the error emitted from  here.

**Comment by codewithtyler** [comment]
This should be fixed with the recent version. If we continue to have problems with this I'll be happy to reopen it.
