### ISSUE TITLE
Some packages will cause build to fail example: "jquery-ui"

### ISSUE THREAD

**Issue by mitermayer** [yatskevich/grunt-bower-task#14]
jquery-ui has a different folder structure now and when specified on component.json will cause the build to fail with an error

**Comment by yatskevich** [comment]
It's an issue in `component.json` in [components/jqueryui](https://github.com/components/jqueryui) repo, because `main` property points to missing file.

But you can take advantage of `exportsOverride` and put the following in your `component.json`:

``` json
{
  "exportsOverride": {
    "jquery-ui": {
      "js": "ui/*.js"
    }
}
```
