### ISSUE TITLE
Why is the "name" property required for a private bower.json?

### ISSUE THREAD

**Issue by JoshMcCullough** [yatskevich/grunt-bower-task#160]
Running `bower install` using the following `bower.json` gives me the error "No name property set". I'm wondering why it's required if it's marked private?

```
{
  "private": true,
  "dependencies": {
    "bootstrap": "~3.3.5",
    "jquery-validate": "~1.14.0",
    "jquery": "~2.1.4"
  }
}
```

**Comment by dejvo** [comment]
It is discussed in https://github.com/bower/spec/issues/22

**Comment by codewithtyler** [comment]
Per @dejvo's comment this issue is part of the bower spec. Any further discussion should be done via the link provided above.
