### ISSUE TITLE
Compatibility with Repository Manager Nexus 3.0

### ISSUE THREAD

**Issue by nicolasrosado** [yatskevich/grunt-bower-task#165]
Hi,

In his latest release, nexus sonatype 3.0 added bower.io format support (https://www.npmjs.com/package/bower-nexus3-resolver).
So now, I want to use grunt-bower-task with this repository manager (to enjoy the new feature proxy for bower).
However, when I do a maven clean install, I meet this error ENAMETOOLONG.

See the stacktrace below : 

[INFO] --- frontend-maven-plugin:0.0.16:grunt (installation node, npm et package nodes) @ project-web ---
[INFO] Running 'grunt --no-color' in /home/nrosado/environnement/source/project/web/src/main/webapp/scripts/lib
[INFO] Running "bower:install" (bower) task
[INFO] >> Cleaned target dir /home/nrosado/environnement/source/project/web/src/main/webapp/scripts/lib/bower_components
[INFO] Fatal error: ENAMETOOLONG, open '/home/nrosado/.cache/bower/registry/localhost%3A8081/lookup/nexus%2Bhttp%3A%2F%2Flocalhost%3A8081%2Fnexus%2Frepository%2Fbower-all%2Fnexus%2Bhttp%3A%2Flocalhost%3A8081%2Fnexus%2Frepository%2Fbower-all%2Fnexus%2Bhttp%3A%2Flocalhost%3A8081%2Fnexus%2Frepository%2Fbower-all%2Fnexus%2Bhttp%3A%2Flocalhost%3A8081%2Fnexus%2Frepository%2Fbower-all%2Fless_e3947'

After discuss with the nexus team, we realized that grunt-bower-task is using ~1.3.0 according to that project's package.json, and the custom resolver functionality that Nexus Repository Manager requires was introduced in ~1.5.0. So grunt task is using an older version of Bower, and that's why we're seeing this, even though my newer version of bower works with Nexus from the command line. Grunt task isn't going to work with Nexus or nexus resolver since the version of bower it depends on is too old to support these newer features. 

I found an alternative that uses a newer version of bower. See below the workaround to avoid to use your grunt-bower-task. To do the same thing, I use :
- "grunt contrib clean" (https://www.npmjs.com/package/grunt-contrib-clean) to clean bower components directory (to have the equivalent of the cleantargetdir option in grunt bower task) 
- and "grunt bower install simple" (https://www.npmjs.com/package/grunt-bower-install-simple) to install bower components (bower 1.7.7 is used in this task)

Could you tell me if you can upgrade the bower version of your "grunt-bower-task" to 1.5.0 or higher in a next release ? If this is the case, could you tell me when the next release is planned ? 

Thanks in advance for your response and your time.

**Comment by codewithtyler** [comment]
@nicolasrosado I've updated the Bower dependency to the latest version. We hope to have a new release soon.
