### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by polpo** [yatskevich/grunt-bower-task#173]
I'm excited to see some new development in this project. However the version on npm, 0.4.0, is 2 years old. Could a new version be published to npm? In particular I am needing some new functionality that is only available in Bower 1.5.x+ .

**Comment by codewithtyler** [comment]
@polpo  I've got one more bug that I'd like to fix before I push a new version to NPM. I hope to have it fixed soon. What functionality in particular are you waiting on?

**Comment by polpo** [comment]
I'm waiting on pluggable resolver support, just like the person who filed issue #165.

**Comment by abyx** [comment]
I'd love a new version to be released as well :+1:

**Comment by codewithtyler** [comment]
I have created a new version on GitHub. Right now I'm just waiting for @yatskevich to update my privileges on the NPM website so I can create a new release there.

**Comment by zeludo** [comment]
I'd like to speed up my CI build by caching bower dependencies and would need the `prune` option in order to ensure the build environment is clean. 
Definitly looking forward to this release too !

**Comment by codewithtyler** [comment]
@yatskevich is there any way we can get this updated?

**Comment by murrayju** [comment]
+1, I'm also waiting on support for bower-art-resolver

**Comment by gumallett** [comment]
+1

**Comment by tanis2000** [comment]
@RandomlyKnighted any chance you're going to push 0.5.0 to npm ?

**Comment by harrisred** [comment]
+1

**Comment by kosdiamantis** [comment]
+1

**Comment by dkart** [comment]
+1

**Comment by codewithtyler** [comment]
Finally got some free time this afternoon to spent on this project again. I've just released v0.5.0 to NPM.
