### ISSUE TITLE
The bower in grunt-bower-task is too old to use Nexus 3 as the bower registry

### ISSUE THREAD

**Issue by Jinshui** [yatskevich/grunt-bower-task#178]
My project uses Nexus 3 as the bower registry, and we use 'grunt-bower-task#0.4' to manage the dependency. The issue is that grunt-bower-task#0.4 depends on bower#1.3 which does not support Nexus 3, the error is as follows when it downloads packages from Nexus:

> Fatal error: ENAMETOOLONG: name too long, open '/Users/jinshui/.cache/bower/registry/xxx.xxx.xxx.xxx%3A9081/lookup/nexus%2Bhttp%3A%2F%2Fxxx.xxx.xxx.xxx%3A9081%2Frepository%2Fbower%2Fnexus%2Bhttp%3A%2Fxxx.xxx.xxx.xxx%3A9081%2Frepository%2Fbower%2Fnexus%2Bhttp%3A%2Fxxx.xxx.xxx.xxx%3A9081%2Frepository%2Fbower%2Fnexus%2Bhttp%3A%2Fxxx.xxx.xxx.xxx%3A9081%2Frepository%2Fbower%2Fblueimp-file-upload_bba27'

where the xxx.xxx.xxx.xxx is the IP address of my Nexus server.

However, when I manually run 'bower install  xxx' with bower 1.8.0, it works fine. 

So, can someone please upgrade the bower dependency to 1.8.0 and publish to the official npm registry at https://www.npmjs.com/package/grunt-bower-task?

Thanks a lot.

**Comment by Jinshui** [comment]
Before this issue gets fixed, the workaround is to remove the node_modules/grunt-bower-task/node_modules/bower before executing grunt-bower-task:
```
grunt.initConfig({
        clean: {
            remove_grunt_bower_task_bower: 'node_modules/grunt-bower-task/node_modules/bower' //grunt-bower-task depends on bower@1.3 which does not support bower repository proxy on Nexus
        }
   }
    grunt.registerTask("build", function() {
        grunt.task.run("clean", "bower:install", "emberTemplates", "concat", "copy-dependencies-resources", "minify", "package");
    });
```

**Comment by codewithtyler** [comment]
@Jinshui does this work if you use bower 1.7.9?

**Comment by Jinshui** [comment]
@tylerbhughes I did not try bower 1.7.9, but I believe it works.

**Comment by codewithtyler** [comment]
Great, version 0.5.0 now uses Bower 1.7.9. I'll go ahead and close this issue but feel free to reopen if you continue to encounter issues.
