### ISSUE TITLE
flag to allowing copying of assets, but no package restoration

### ISSUE THREAD

**Issue by Iristyle** [yatskevich/grunt-bower-task#18]
Running bower on every build can be expensive, depending on how you're using Grunt.

I would like to be able to add a value to options that allows for packages to still be copied from `components` to the final output directory, but I'd like to skip the calls to Bower itself.

I implemented a `--skipBower` flag in my Grunt build, but then realized I didn't have a way of using `grunt-bower-task`  **without** it calling Bower to restore packages.

I need this because I always call `clean` on my output directory before my build starts.

Thanks!

**Comment by yatskevich** [comment]
Fixed in version 0.2.1
