### ISSUE TITLE
Nothing copied to TargetDir

### ISSUE THREAD

**Issue by M0nter0** [yatskevich/grunt-bower-task#180]
Running 
```
 bower: {
            install: {
                options: {
                    targetDir: "./Scripts/bower_target",
                    cleanTargetDir: true, //This works
                    verbose: true
                }
            }
        }
```
It doesn't copy anything to the targetDir. It cleans the targetDir folder, but then it doesn't refill it. Of course, I've check that the files are already at `bower `folder.

When I run the task `cmd.exe /c grunt -b` the output is just:
```
bower:install --color
Running "bower:install" (bower) task
bower.json validation: Passed
>> Installed bower packages
Done, without errors.
Process terminated with code 0.
```

Using:
├── bower@1.8.0
├── grunt@1.0.1
├── grunt-bower-task@0.5.0 //Tried also with 0.4.0 with the same results
├── ...

I've already check #158, #137 and #134 without success.
Any idea??

**Comment by codewithtyler** [comment]
Try adding `copy: true` to your config.

**Comment by M0nter0** [comment]
It Works! Thanks, @tylerbhughes 👍
