### ISSUE TITLE
First install components than delete them

### ISSUE THREAD

**Issue by Fires04** [yatskevich/grunt-bower-task#181]
Hi, maybe I just do not understand how this package works maybe it is a bug:

```
bower: {
            install: {
                options: {
                    targetDir: './assets/',
                    cleanBowerDir: true
                }
            }
        },
Running "bower:install" (bower) task
Verifying property bower.install exists in config...OK
File: [no files]
Options: cleanTargetDir=false, cleanBowerDir, targetDir="./assets/", layout="byType", install, prune=false, verbose=false, copy=false, bowerOptions={}bower invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower cached https://github.com/twbs/bootstrap.git#3.3.7
bower validate 3.3.7 against https://github.com/twbs/bootstrap.git#^3.3.7
bower cached https://github.com/jquery/jquery-dist.git#3.2.1
bower validate 3.2.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower install bootstrap#3.3.7
bower install jquery#3.2.1
>> Installed bower packages
>> Cleaned bower dir C:\wamp64\www\projectglobe\bower_components

Done.
```

The module first downloads the components and after that delete the whole folder. Is it alright? I think If I set cleanBowerDir: true it should remove bowerDir and download new data.

**Comment by codewithtyler** [comment]
Right, it's deleting your files because you never added 'copy: true' to your config.

The way this package works is it supports the default bower settings which means it will download to bower directory. You have to tell if you want it to do something else.

**Comment by Fires04** [comment]
Hi, thanks so I'm just stupid :(

**Comment by codewithtyler** [comment]
@Fires04 nah, it's a common mistake. When I first started working on the project I made the same mistake. Perhaps the documentation for this just needs to be improved. If you want to improve that to help others you're welcome to make a Pull Request and I'll approve it.
