### ISSUE TITLE
bower repository migration, upgrade

### ISSUE THREAD

**Issue by vir-c** [yatskevich/grunt-bower-task#182]
The Bower registry has been moved from 'https://bower.herokuapp.com' to  'https://registry.bower.io'
update to new release
Please refer the below links for more details:

https://gist.github.com/sheerun/c04d856a7a368bad2896ff0c4958cb00
https://twitter.com/bower/status/918073147789889536

**Comment by codewithtyler** [comment]
@vir-c that URL isn't hardcoded into the project. As long as you fix this in your .bowerrc file then grunt-bower-task should respect it. I'm going to close this for now but if you see any issue with grunt-bower-task not respecting the setting feel free to reopen.

**Comment by vir-c** [comment]
It is pointed out by the bower community that **.bowerrc is not the recommended way**. 
Please upgrade the bower version. 
Also for any newbie unfamiliar with the registry switch `grunt-bower-task` will _automatically fail_. The fix should be in the package.  
Please refer the comments in this tweet: https://twitter.com/bower/status/918073147789889536
