### ISSUE TITLE
Node 0.10 support

### ISSUE THREAD

**Issue by Iristyle** [yatskevich/grunt-bower-task#22]
This is more of a placeholder than anything else... at the moment, there's nothing you can do.  Bower is stuck waiting on `unzip` and a few others NPM packages to be fixed before they'll fully support Node 0.10.

I tried the `0.8.6` version of Bower which is supposed to work, but in my case, it didn't.

https://github.com/twitter/bower/issues/337
https://github.com/twitter/bower/issues/312
https://github.com/twitter/bower/issues/314

**Comment by Globegitter** [comment]
I am getting some random errors sometime (so it seems), was just going to open up a git issue for that,but maybe it is just an issue with Node 0.10: Basically when I run grunt bower, it says everything done fine.

But then it just did not download: Source file "app/lib/d3/d3.js" not found.

And sometimes I get (when running grunt bower):
Fatal error: ENOTEMPTY, rmdir 'somepath\app\components\ember.git\objects'
and just I got
Fatal error: EPERM, unlink in '...\ember.git\objects\pack\pack-9224aec56ae3d846f7aa398591c3b74a47a7e975.idx'

This is all on windows btw. I know this are no detailed error messages right now but I will try to provide more details when I find more time.

EDIT: Ok, the d3.js error just comes up with 3.1.5 but not with 3.1.4

**Comment by GraemeF** [comment]
Looks related to isaacs/rimraf#21.

**Comment by Iristyle** [comment]
@yatskevich Node 0.10 is covered in Bower [0.9.0](https://github.com/bower/bower/blob/master/CHANGELOG.md#090---2013-04-25)+

It fixes one of the bigger bugs in temp file management as well that has been plaguing me - https://github.com/bower/bower/issues/345

Note that this version also includes support for the rename from `component.json` to `bower.json` -- but fortunately it is designed to fallback so this shouldn't be an issue.

https://github.com/bower/bower/blob/909dca8f9a02d3fd1f5aaebb1b94c6ccefd993aa/test/manager.js#L89

**Comment by gkorland** [comment]
I still see it with node.js v0.10.7 and bower v1.0.0

``` json
{
  "name": "My Project",
  "version": "1.0.0",
  "main": "js/main.js",
  "dependencies": {
    "jquery": "1.10.2",
    "jquery-ui": "1.10.3",
    "jquery.cookie": "1.3.1",
    "backbone": "1.0.0",
    "backbone.babysitter": "0.0.6",
    "backbone.eventbinder": "1.0.2",
    "backbone.marionette": "1.0.4",
    "backbone.mutators": "0.4.0",
    "backbone.wreqr": "0.2.0",
    "backbone.localStorage": "1.1.6",
    "backbone-deep-model": "0.10.4",
    "bootstrap": "2.3.2",
    "font-awesome": "3.2.1",
    "bootstrap-tour": "0.5.0",
    "x-editable": "1.4.5",
    "underscore": "1.5.1",
    "requirejs": "2.1.8",
    "purl": "2.3.1",
    "text": "2.0.7",
    "iscroll": "5.0.4"
  },
  "resolutions": {
    "jquery": "1.10.2",
    "underscore": "1.5.1",
    "bootstrap": "2.3.2"
  }
}
```

It seems like the error happens on x-editable install

**Comment by p3k** [comment]
Still happening with node 0.10.15 and bower 1.0.3:

``` json
{
  "name": "test",
  "version": "0.0.0",
  "main": ["./js/test.js"],
  "dependencies": {
    "file-api": "https://github.com/mailru/FileAPI/archive/gh-pages.zip",
    "jquery-jsonrpc": "https://github.com/datagraph/jquery-jsonrpc/archive/master.zip"
  }
}
```

**Comment by amaltson** [comment]
Still happening with node 0.10.15 and bower 1.3.3
