### ISSUE TITLE
Install bower files only

### ISSUE THREAD

**Issue by jrschumacher** [yatskevich/grunt-bower-task#3]
I would like to be able to install bower files only and not copy them to a alternative directory.

Suggested:

``` js
{
  targetDir: false // disable copying files
} 
```

**Comment by jrschumacher** [comment]
I didn't realize how useful this is with respect to building various libraries. However I am having an issue with a library listed on bower.

```
Fatal error: ENOENT, no such file or directory 'components/angular-strap/build/angular-strap.min.js'
```

In `components/angular-strap/` is a `dist` dir which contains the needed files. How is bower pulling this information?

**Comment by yatskevich** [comment]
Bower uses version of the library as a git tag.
In your case `angular-strap` has [several tags](https://github.com/mgcrea/angular-strap/tags), starting from the version `v0.5.8` they've renamed `build` to `dist`.
