### ISSUE TITLE
install: false doesn't appear to work

### ISSUE THREAD

**Issue by Iristyle** [yatskevich/grunt-bower-task#35]
I'm trying to use the new `install` option to prevent the installation of packages from occurring when I already have them.

As soon as I set `install` to `false`, my grunt build dies at `grunt-bower-task` -- no failure, warning or other messages -- it just stops dead in it's track (and I always run Grunt in `verbose` mode).

I seem to be able to toggle any of the other options without a problem, but `install` is having issues.

**Comment by fantactuka** [comment]
Can you show your task config? I've just tried the one below and it works as expected:

``` js
bower: {
  dummy: {
    options: {
      install: false
    }
  },
  install: {
  }
}
```

If I do `grunt bower:dummy` without any components installed — nothing happens, since task have nothing to copy. If I do `grunt bower:install && grunt bower:dummy` then on the second step it runs copy task without installation.

**Comment by Iristyle** [comment]
My Grunt config is much longer than this, but the basic idea is... I use this for default config:

``` coffeescript
taskConfig =
  bower:
    lib:
      options:
        install: true
        copy: true
        cleanTargetDir: true
        cleanBowerDir: true
        targetDir: 'generated/lib/'
        verbose: true
```

Then when grunt is loaded, I check for the option `skipBower`, specified at the cmd line by `--skipBower=true` and only honor it when the `components` folder exists.

``` coffeescript
  skipBower = grunt.option('skipBower') || false
  bowerExists = fs.existsSync(path.join(__dirname, 'components'))

  if (skipBower)
    if (bowerExists)
      # sanity check to see what config looks like before
      console.log(taskConfig.bower.lib)

      grunt.log.writeln(('[notice]').yellow + ' skipping Bower package restore')
      bowerOpts = taskConfig.bower.lib.options
      bowerOpts.install = false
      bowerOpts.cleanBowerDir = false

      # and after modifications
      console.log(taskConfig.bower.lib)
    else
      msg = '--skipBower ignored since Bower folder does not exist'
      grunt.log.writeln(('[notice]').yellow + msg)


  grunt.initConfig(taskConfig)
```

My log message `skipping Bower package restore` is shown, but then, as mentioned, actual execution of the task  doesn't happen.

I also tried by just changing the default config and not using the `skipBower` option like this:

``` coffeescript
taskConfig =
  bower:
    lib:
      options:
        install: false
        copy: true
        cleanTargetDir: true
        cleanBowerDir: false
        targetDir: 'generated/lib/'
        verbose: true
```

This didn't work either.

Normally I'd debug in and see what's going on here, but I've been a bit short on time.

Thanks!

**Comment by fantactuka** [comment]
@Iristyle Does the issue still relevant? Works fine for me with the latest, would be great if you can check yours.
