### ISSUE TITLE
Problems running `bower` task inside a Vagrant VM

### ISSUE THREAD

**Issue by beaumartinez** [yatskevich/grunt-bower-task#37]
I'm trying to call the `bower` task inside a Vagrant VM at my project's root (`/vagrant`, which points to a folder outside the Vagrant VM).

When I call it outside the Vagrant VM—on my normal command line—it works fine, however, inside the Vagrant VM I get—

```
Running "bower:install" (bower) task
Fatal error: spawn ENOENT
```

I think the error occurs within `bower.commands.install()`; I'm going to assume it happens because `/vagrant` isn't a "normal" folder.

Have you seen this kind of issue before?

**Comment by beaumartinez** [comment]
I tried changing settings on my VM [as suggested on a similar Vagrant issue](https://github.com/mitchellh/vagrant/issues/713#issuecomment-16935265) to no avail.

**Comment by beaumartinez** [comment]
Some progress—I realised the `bower` command uses `git`, so I installed it. When I run the `grunt` task, now I get—

```
{ [Error: status code of git: 255]
  details: 'error: cannot open .git/FETCH_HEAD: Permission denied\n\n',
  command: 'git',
  code: 255 }
Fatal error: status code of git: 255
```

**Comment by beaumartinez** [comment]
Running the `bower install` command, I get output like—

```
bower fetching handlebars
bower caching git://github.com/timrwood/moment.git
bower error EACCES, mkdir '/home/vagrant/.bower/cache/moment'
bower error status code of git: 128
```

Trying `sudo bower install` I get—

```
bower fetching handlebars
bower caching git://github.com/timrwood/moment
bower error status code of git: 128
```

(No EACCESS this time.)

**Comment by beaumartinez** [comment]
Looks like there are some general `bower` issues directly causing this this.

**Comment by fantactuka** [comment]
There's a thread about this issue (I remember there were couple more): bower/bower#50.

**Comment by beaumartinez** [comment]
Nice one @fantactuka! Since it is a `bower` issue, I'll close this issue.

**Comment by fantactuka** [comment]
@beaumartinez actually, i might be wrong to refer that bower issue, it most likely permissions issue on you VM rather than bower's. So I'd check permissions and try to switch from git:// to https:// for bower (as noted in bower/bower#50)
