### ISSUE TITLE
any plan to add image support?

### ISSUE THREAD

**Issue by houqp** [yatskevich/grunt-bower-task#41]
Thanks, for this awesome task :)

I have a project that needs to split vendor library into js, css and img folder. Seems that currently only css and js are supported?

**Comment by fantactuka** [comment]
Nope, it's not limited by file types. The key (`js`, `css`, `img`, etc.) is just a "group" name, not a file type, so you can use something like this:

``` json
  "exportsOverride": {
    "bootstrap-sass": {
      "js": "docs/assets/js/bootstrap.js",
      "css": "lib/*.css",
      "img": "img/*.png"
    }
  }

```

**Comment by houqp** [comment]
ha, nice! thanks for your help!
