### ISSUE TITLE
layout option not working

### ISSUE THREAD

**Issue by mokkabonna** [yatskevich/grunt-bower-task#42]
I have tried no option (so byType), and explicitly bytype and byComponent, neither seems to do any good. Testing with bootstrap. Expects js and css in different folders. End up in same folder.

It looks like this.

```
lib
 |
 --bootstrap
    |
    --bootstrap.css
    --bootstrap.js
```

**Comment by xdissent** [comment]
Also only attempts to copy the first package.

**Comment by yatskevich** [comment]
@mokkabonna Is this issue resolved?

**Comment by mokkabonna** [comment]
Depends, maybe I've misunderstood. I assumed it would work automatically, detecting js/css by the filename.

Or does it have to be defined in exportsOverride for it to get sorted like that?

**Comment by mokkabonna** [comment]
This is how my project gets organized now

default (byType)

```
app/vendor/
├── bootstrap
│   ├── bootstrap.css
│   └── bootstrap.js
├── css
│   └── qunit
│       └── qunit.css
├── jquery
│   └── jquery.js
├── js
│   ├── qunit
│   │   └── qunit.js
│   └── requirejs
│       └── require.js
└── knockout.js
    └── knockout.js

byComponent

app/vendor/
├── bootstrap
│   ├── bootstrap.css
│   └── bootstrap.js
├── jquery
│   └── jquery.js
├── knockout.js
│   └── knockout.js
├── qunit
│   ├── css
│   │   └── qunit.css
│   └── js
│       └── qunit.js
└── requirejs
    └── js
        └── require.js
```

I have this bower.json config

```
  "dependencies": {
    "knockout.js": ">=2.0.0",
    "jquery": ">=1.9.0"
  },
  "devDependencies": {
    "requirejs": "2.0.6",
    "qunit": "~1.12.0",
    "bootstrap": "~3.0.0"
  },
  "exportsOverride": {
    "requirejs": {
      "js": "require.js"
    },
    "qunit": {
      "js": "qunit/qunit.js",
      "css": "qunit/qunit.css"
    }
  }
```

I have overrides for requirejs and qunit because they don't have a main file. For the others I assumed grunt-bower-task would still sort the main files into groups like js/css.

**Comment by mokkabonna** [comment]
This is with 0.3.1

**Comment by mokkabonna** [comment]
I see that you handle untyped this way https://github.com/yatskevich/grunt-bower-task/blob/6e961159ff9c9efc65e6ccb73b2f9df2ea7708fc/tasks/lib/layouts_manager.js#L4

What about having a overridable function like this:

```
//default return type by filename
determineType : function(filename, component) {
    return path.extname(filename).substr(1); 
}
```

This way for the most part types will be determined by the extension. But it also allows the user to do whatever he wants in a self supplied function. Liek analyze the contents of the file and determine it that way if extension enough.

Or maybe just pass an extra argument to the layout function that is the filename, and the user can do it there.

**Comment by yatskevich** [comment]
@mokkabonna you're right. We intentionally called the layout `byType` and use the word 'type' instead of 'extension'. This abstraction allows to use names for groups of assets different from extension. So you can put your JavaScripts in `javascripts` group, CSS/LESS/SCSS in `stylesheets` group and so on.

Thanks to this issue we've realised that grouping by _extension_ is a common use-case. In the next version we'll add `filename` to the parameters of layout function and provide `byExtension` layout.

**Comment by mokkabonna** [comment]
Sounds great, adding filename to the function will allow for much better control in determining the desired layout.
