### ISSUE TITLE
WIndows - Intermittent missing directories error

### ISSUE THREAD

**Issue by roytruelove** [yatskevich/grunt-bower-task#44]
Versions:
- grunt-bower-task 0.2.3
- Windows 7 64 bit
- Node 10.13 64 bit
- grunt-cli v0.1.8
- grunt v0.4.0

Error is:
`Fatal error: ENOENT, no such file or directory 'C:\myProject\components\jscache'`

I get this error intermittently.  I first clean the `components` dir, then run `install` with a `targetDir` of `components`.  I'd expect the bower component to create this directory.

For this test I've honed the `bower.json` file to simply this:

```
{
  "dependencies": {
    "jscache":"latest"
  }
}
```

If I run the same `grunt clean bower` command over and over again, sometimes I get the error, sometimes not.  Here's a full sample of the output:

```
mets-client$ grunt clean bower
Running "clean:all" (clean) task
Cleaning "components"...OK

Running "bower:install" (bower) task
>> Installed bower packages
Fatal error: ENOENT, no such file or directory 'C:\myProject\components\jscache'
mets-client$ grunt clean bower
Running "clean:all" (clean) task
Cleaning "components"...OK

Running "bower:install" (bower) task
>> Installed bower packages
```

If I run bower directly from the command line I get no issues.

**Comment by fantactuka** [comment]
Does not sound like an issue, but a misuse. Please consider following:

If you want only install bower components without benefits of `exportsOverride` — configure it:

``` js
{
  options: {
    install: true,
    copy: false  
  }
}
```

If you want to use `exportsOverride` then you have to specify `targetDir` different to `components`. Bower will install its components into `components` dir and after that copy files per `exportsOverride` rules into `targetDir`.
