### ISSUE TITLE
read package.json file too, better filtering

### ISSUE THREAD

**Issue by rolandjitsu** [yatskevich/grunt-bower-task#46]
Would it be possible to read the `package.json` file too ? Because it does seem like some repositories don't have a `bower.json` or `components.json` file, but they specify the main fail tough inside their `package.json`.

Also what could I do to filter for instance the modernizr repository ? Because it doesn't have a `package.json` nor a `bower.json` or anything that could tell us which is the main file. I was thinking of using the folder name, or the name of the repository to Regex find something that contains that name ?

**Comment by yatskevich** [comment]
@rolandjitsu grunt-bower-task allows you to specify all needed files / wildcards / regexes in your `bower.json` in `exportsOverride` section. 
The task will copy requested files to `./lib` directory regardless of `components.json`/`bower.json`/`package.json` presence.
