### ISSUE TITLE
the wildcard option might not work properly

### ISSUE THREAD

**Issue by rolandjitsu** [yatskevich/grunt-bower-task#47]
I have the following `bower.json`:

<pre>
{
    "name": "DrawerJS",
    "version": "0.0.0",
    "main": "src/drawer.js",

    "ignore": [
        
        ".bowerrc",
        "*.env",
        ".gitignore",
        "*.json",
        "*.md",
        "*.js",
        "*.txt",
        "Procfile",
        "components/*",
        "docs/**",
        "node_modules/**",
        "public/**"
    ],

    "dependencies": {},

    "devDependencies": {
        
        "jquery": "2.0.3",
        "modernizr": "2.6.2",
        "underscore": "1.5.1",
        "angular-unstable": "1.1.5"
    },

    "exportsOverride": {

        "modernizr": {

            "/js/vendor/": "modernizr.js"
        },
        
        "underscore": {
            
            "/js/vendor/": "underscore.js"
        },

        "*": {

            "/js/vendor/": "*.js"   
        }
    }
}
</pre>

And the grunt task is configured as such:

<pre>
bower: {

    options: {

        targetDir: "./public/"
    },

    install: {}
}
</pre>

According to you documentation and to my settings all the js folders / files with the dependencies should be going to `/public/js/vendor/nameOfDependency/someFile.js`. But instead, whatever comes after I define how should `modernizr` and `underscore` behave goes to `/public/nameOfDependency/someFile.js`. I think that this should not be happening, as you documented, whatever is handled by the wildcard should be thrown intto the `/public/js/vendor/` folder too, but it isn't.

Am I doing the configuration wrong or is it a bug ?

**Comment by yatskevich** [comment]
Wildcard feature is available only in 'devel' branch. We're going to publish updated npm module soon.

Are you testing devel branch?

**Comment by rolandjitsu** [comment]
Well that makes sense, I'm downloading the npm published version so maybe that is why :) Thanks for the tip and looking forward for the wildcard feature :+1:
