### ISSUE TITLE
not installing packages

### ISSUE THREAD

**Issue by chrismatheson** [yatskevich/grunt-bower-task#48]
Hi,

I was hopping to use this grunt plugin to effectively use bower without the dependency of bower cli.

my current settings are 

``` javascript
        bower: {
            install: {
                options: {
                    targetDir:"src/common",
                    layout:"byComponent",
                    cleanBowerDir:true,
                    install:true
                }
            }
        },
```

which i expected would look at my bower.json file and then install those components into src/common directory and leave no trace of bower_components directory etc

i dont get any files but also no errors. am i missing something?

```
>> Installed bower packages
Reading /Users/chrismatheson/iv/iVendi-angular/bower.json...OK
Parsing /Users/chrismatheson/iv/iVendi-angular/bower.json...OK
```

any help would be great, thanks.

**Comment by yatskevich** [comment]
@chrismatheson Could you please post the contents of your `bower.json` if the issue still exists?

**Comment by chrismatheson** [comment]
``` javascript
{
  "name": "iVendi-angular",
  "version": "0.1.0",
  "main": "index.html",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

**Comment by chrismatheson** [comment]
i have not looked at this recently. ill try and find some time to investigate a little further. Does what im trying to do make sense?

i effectivly want my dependencies to be install automatically by grunt & to the `src/common/<some component name>/<componenet code>` directories

**Comment by yatskevich** [comment]
@chrismatheson hmm, your `bower.json` does not have any declared dependencies.
