### ISSUE TITLE
Add CWD option where bower will run 

### ISSUE THREAD

**Issue by Xumeiquer** [yatskevich/grunt-bower-task#53]
``` js
bower: {
            install: {
                options: {
                    cwd: "<%= meta.target %>",
                    targetDir: '<%= meta.target %>/Libraries',
                    layout: 'byType',
                    install: true,
                    verbose: true,
                    cleanTargetDir: false,
                    cleanBowerDir: false
                }
            }
        },
```

**Comment by yatskevich** [comment]
Could you please explain the reason why do you need this feature?

**Comment by Xumeiquer** [comment]
According to the new bower specification you can store the .bowerrc in some of these places plus command line.
- local bowerrc located in the cwd
- all bowerrc files upwards the directory tree
- bowerrc located in the home folder
- bowerrc located in the global folder

and if moreover you add the field `"directory": "BowerLib"` in .bowerc, for example.

Each time that you will run the bower-task, it will create BowerLib folder (if needed) in the cwd where "bower-task" is running, so adding this option, you will be free to run the "bower-task" elsewhere inside your source folder, e.g. target/, generating target/BowerLib instead of BowerLib in the cwd where grunt is running.

Although, you can change the `"directory": "BowerLib"` in .bowerc by `"directory": "target/BowerLib"`, but in this case you are losing that flexibility, since .bowerrc can be placed in /home/<USER> and that means the configuration file will be generic for most of the projects.

**Comment by yatskevich** [comment]
@Xumeiquer Could you please take a look at #64 ? Does this PR implement proposed feature?

**Comment by Xumeiquer** [comment]
I checked it out and I think it will sort out the issue
