### ISSUE TITLE
Seeing error message after succesfull bower install

### ISSUE THREAD

**Issue by awaterma** [yatskevich/grunt-bower-task#56]
Hi,

I'm seeing the following error message when I complete a bower install with the grunt-bower-task. Bower installs the dependency correctly, but I still get an error message. This reproduces for me with both specified options and not. 

Error:

> > Installed bower packages
> > Fatal error: Arguments to path.join must be strings

Configuration:

 1    module.exports = function(grunt) {
  2   grunt.loadNpmTasks('grunt-bower-task');
  3
  4   grunt.initConfig({
  5     pkg: grunt.file.readJSON('package.json'),
  6     bower: {
  7       install: {
  8         options: {
  9           targetDir: 'src/public',
 10           layout: 'byType',
 11           install: true,
 12           verbose: false,
 13           cleanTargetDir: false,
 14           cleanBowerDir: false
 15         }
 16        }
 17     }
 18   });
 19 };

This is available in a public project. I will be pushing the change later today:

https://github.com/ecosur-infonomia/directorio

**Comment by rossedman** [comment]
This is also happening to me and I have very similar settings

**Comment by dreambrother** [comment]
+1

node v0.10.15
grunt v0.4.1
grunt-bower-task: ~0.3.0

**Comment by dreambrother** [comment]
doesn't reproduce on grunt-bower-task v0.2.3

**Comment by awaterma** [comment]
I also see this working properly if I rollback to v0.2.3.

Here's some more information from my local installation:

directory-app(master) ✗: grunt --version
grunt-cli v0.1.9
grunt v0.4.1

directory-app(master) ✗: node -v
v0.10.13

**Comment by awaterma** [comment]
I'm not sure if this bug has been logged, but after rolling back to 0.2.3, neither my .bowerrc nor my target directory in my Gruntfile configuration is honored. Dependencies are only installed to the "lib" folder; so this won't work as a workaround solution for me. :(

**Comment by rossedman** [comment]
grunt 0.4.1
bower 1.1.0
bowertask 0.3.0
node 0.10.13
npm 1.3.2

Seems like we all have similar configurations. So I shouldn't roll back to 0.2.3? Anyone have an idea of what could be the reason for this?

**Comment by rossedman** [comment]
Could this be because of our bower version? I don't know about you guys but I am using bower 1.1.0. 

https://github.com/yatskevich/grunt-bower-task/pull/57 - Support 1.1.0 branch hasn't been merged yet, I think.

**Comment by yatskevich** [comment]
Version 0.3.1 has been just released. Could you please verify that the issue is fixed now?

**Comment by joseym** [comment]
#57 resolved it for me.

**Comment by dreambrother** [comment]
In v0.3.1 error is not reproduced, but with the default bower configuration

```
 bower: {
            install: {                
            }
        }
```

, I can't see all of my dependencies in the 'lib' folder. Etc., 

```
"dependencies": {
        "angular": "1.0.7",
        "bootstrap": "2.3.2",
        "jquery": "2.0.3"
    }
```

There is only 'angular' in the 'lib'.

Is it expected behavior?

**Comment by dreambrother** [comment]
In the 'bower_components' folder, I see all of the declared dependencies.

**Comment by awaterma** [comment]
0.3.1 resolves the issue for me. I'm closing the issue. Thank you so much for the speedy and excellent fix! The node community always amazes! :)

:8ball:
