### ISSUE TITLE
How do I install a bower package?

### ISSUE THREAD

**Issue by mhulse** [yatskevich/grunt-bower-task#58]
First, thanks for this task! Looks awesome. I can't wait to use Bower in my Grunt workflows. :+1: 

With that said, I can't figure out how to install packages.

I'm sure it's obvious, but ... The docs don't have an example of what to do once you've setup all the Grunt requirements.

For example, I'd like to install [normalize.css](http://necolas.github.io/normalize.css/), which says:

> …or install with Bower.
> 
> ```
> bower install --save normalize-css
> ```

How do I translate that to `grunt-bower-task` speak?

Do I need to setup a `bower.json`?

Sorry, the `README` doesn't mention any of this (unless I missed it) and I'm new to Bower, so I'm left scratching my head.

I'll post back here if/when I figure it out (I'm sure this info will help other Bower noobs like me).

**Comment by mhulse** [comment]
So, I figured it out.

On top of all the Grunt-related setups detailed in the README, for example:

``` js
// ...

/*----------------------------------( BOWER )----------------------------------*/

/**
 * Install Bower packages. Smartly.
 *
 * @see https://github.com/yatskevich/grunt-bower-task
 * @see http://bower.io/
 */

bower : {

    install : {

        options : {

            targetDir : './files/plugins', // A directory where you want to keep your Bower packages.
            cleanup: true, // Will clean target and bower directories.
            verbose: true, // Debug output.

        },

    },

},

// ...

/*----------------------------------( TASKS )----------------------------------*/

grunt.loadNpmTasks('grunt-bower-task');

// ...

```

... I had to create a `bower.json` file and put it next to my `Gruntfile.js`.

Looks like the bare minimum requirements to have in this file are:

``` json
{
  "name": "your-project-name",
  "version": "0.0.0",
  "dependencies": {
    "normalize-css": "2.1.2"
  }
}
```

From there, I ran `$ grunt bower` (`$ grunt bower:install` works too) and everything installed without a hitch.

### Question:

Why do I need to specify a `name` and `version` in my `bower.json` file? These two settings seem a tad superfluous.

I already have this info in my `package.json` file ... Too bad I can't utilize the settings from there in order to populate the values of `name` and `version` in `bower.json`.

Then again, I'm assuming it's best practice to fill-in `name` and `version` with the `name` and `version` being used in my `package.json` file? No?

Thanks again for this awesome plugin! :+1:  :octocat:

**Comment by yatskevich** [comment]
@mhulse Thing is that Bower component is not always Node.js module/app so it's okay that you have to specify `name` and `version` in both files.

**Comment by mhulse** [comment]
Thanks for the clarification @yatskevich! Much appreciated.
