### ISSUE TITLE
[Proposal] Validate the bower.json

### ISSUE THREAD

**Issue by thomaswelton** [yatskevich/grunt-bower-task#67]
I've recently upgraded to bower 1.0
Running the grunt task failed with this error.

```
Running "bower_install:install" (bower_install) task
Fatal error: Failed to read /Users/thomaswelton/Sites/nokia-925/bower.json
```

After a little while I ran `bower install` outside of grunt from the terminal and got a much more useful error message.

```
bower EINVALID Failed to read /Users/thomaswelton/Sites/nokia-925/bower.json

Additional error details:
No name property set
```

Bower has a command to validate the bower.json https://github.com/bower/json
Looks like this may return useful messages.

Maybe we should add in validation and return more useful error messages by default. This may be useful if the requirements of the bower spec change again in the future.
Happy to submit a PR, let me know your thoughts.

**Comment by yatskevich** [comment]
@thomaswelton good idea! We'll be glad to see the PR :+1:

**Comment by codewithtyler** [comment]
@thomaswelton are you still interested in submitting a PR to fix this issue?

**Comment by thomaswelton** [comment]
Don't really use grunt much more so haven't used this plugin for a while. So no sorry.

**Comment by codewithtyler** [comment]
That's fine. Thanks for following up with me.

**Comment by codewithtyler** [comment]
I've started working on this. I hope to have a PR with this done soon.

**Comment by codewithtyler** [comment]
I just added this feature via commit 9b85b58a831741264c811dfcfbd5f35ff0f9c6a. By default grunt-bower-task will check for an valid bower.json file and will display an error message if it is invalid. However, it will only display a success message if the verbose flag is enabled.
