### ISSUE TITLE
Packages with multiple main files fail to install

### ISSUE THREAD

**Issue by fiskeben** [yatskevich/grunt-bower-task#69]
If the value of a package's `main` attribute is an array, the paths in that array are joined into one string and installation fails.

This seems to be due to a bug in the `list` command in Bower. At least diffing the version `grunt-bower-task` depends on (in my case it installed 1.1.2) with the latest (1.2.4) the `join(',')` has been removed.

A solution would be to upgrade Bower.

**Comment by yatskevich** [comment]
Will be fixed by #70
