### ISSUE TITLE
Duplicate filename = remove

### ISSUE THREAD

**Issue by kirkas** [yatskevich/grunt-bower-task#77]
For project that happened to have a few file with the same name, grunt-bower-task with "layout":"byType" + exportOverride only take the last instance of file.

Exemple:

Bourbon.io:

"/app/assets/stylesheets/css3/_linear-gradient.scss"
"/app/assets/stylesheets/functions/_linear-gradient.scss"

Same file name but different folder, grunt-bower-task will copy only the last one.

**Comment by yatskevich** [comment]
@kirkas could you please show me your `bower.json`?

**Comment by kirkas** [comment]
``` json
{
  "name": "Bluefields",
  "version": "0.1.0",
  "dependencies": {
    "jquery": "1.9.1",
    "jquery-ui": "latest",
    "underscore": "latest",
    "backbone": "latest",
    "backbone-relational": "latest",
    "marionette": "latest",
    "bourbon": "latest",
    "momentjs": "latest",
    "fastclick": "latest",
    "spinjs": "latest",
    "jquery-autosize": "latest",
    "jquery.transit": "latest",
    "backbone.hammer.js": "~0.1.0",
    "hammerjs": "~1.0.5"
  },
  "resolutions": {
    "jquery": "1.9.1"
  },
  "exportsOverride": {
    "*": {
      "js": "**/*.js",
      "scss": "**/*.scss"
    }
  }
}
```

**Comment by yatskevich** [comment]
@kirkas you may try to modify your `exportsOverride` as follows:

``` json
{
  "exportsOverride": {
    "bourbon": {
      "scss": "app/assets/stylesheets"
    },
    "*": {
      "js": "**/*.js",
      "scss": "**/*.scss"
    }
  }
}
```

When you specify directory (_app/assets/stylesheets_) instead of wildcard (_*_/_.scss_), then the task will copy the contents of this directory.

**Comment by kirkas** [comment]
That worked like a charm, thank you very much!
