### ISSUE TITLE
Bower folder inside node_modules - too deep folder structure on win

### ISSUE THREAD

**Issue by Nabla128k** [yatskevich/grunt-bower-task#78]
(Note: I'm total newbie in this area, so - sorry if this a bad way to ask)
Is it possible/sane/logic to set up grunt-bower-task to use globally installed bower?
I'm playing with mean stack on win and grunt-bower-task installs bower locally and it leads to very long paths which can be problem on windows - e.g.:

c:...\mean-test\node_modules\grunt-bower-task\node_modules\bower\node_modules\update-notifier\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-stream-auto-pause.js

If my ...\ part is not very short (which is not), the path exceeds windows path length limit.
Thanks

**Comment by yatskevich** [comment]
@Nabla128k I don't think this is the issue in grunt-bower-task. Potentially, any npm package may cause such a long path. This is the way nodejs/npm works.
