### ISSUE TITLE
How does overrides work?

### ISSUE THREAD

**Issue by reggi** [yatskevich/grunt-bower-task#79]
Ideally I could do something where I replace the main file with something like this.

```
"overrides": {
  "font-awesome": {
    "main": [
      "css/font-awesome.min.css",
      "font/FontAwesome.otf",
      "font/fontawesome-webfont.eot",
      "font/fontawesome-webfont.svg",
      "font/fontawesome-webfont.ttf",
      "font/fontawesome-webfont.woff"
    ]
  }
}
```

I posted something [here](http://stackoverflow.com/questions/19251931/simlink-or-copy-files-out-of-bower-component) about it, I'm very frustrated with bower and grunt.

**Comment by yatskevich** [comment]
@reggi you may find this section useful - https://github.com/yatskevich/grunt-bower-task#advanced-usage
