### ISSUE TITLE
exclude dev-dependencies when copying dependencies to target directory

### ISSUE THREAD

**Issue by travi** [yatskevich/grunt-bower-task#89]
dev-dependencies are defined as such because they are not needed for the production system. Therefore, they shouldn't be copied to the target directory.

**Comment by yatskevich** [comment]
Take a look at `bowerOptions` which @xzyfer added support for. This option is available since version 0.3.3. 
You should specify `production: true` if you want only production files to be filtered and copied.

**Comment by travi** [comment]
While that does remove the dev-dependencies from the target directory, it's not quite what I'm looking for because it also removes them from the bower_components directory. I still need those dependencies for other tasks, but it does not make sense to move them to the directory that then gets packaged with the rest of the site for deployment.
